namespace PhotoArchive.Import;

internal sealed record ManifestColumnIndexes(
    int ImportBatchId,
    int SourcePath,
    int OutputPath,
    int Bucket,
    int Sha256,
    int SizeBytes,
    int Extension,
    int Width,
    int Height,
    int Orientation,
    int CameraMake,
    int CameraModel,
    int ExifTags,
    int ExifDateTimeOriginal,
    int ExifCreateDate,
    int ExifModifyDate,
    int FolderDateCandidate,
    int CreatedAtUtc,
    int LastWriteAtUtc,
    int CleanerBestDate,
    int CleanerBestDateSource,
    int GroupingYear,
    int GroupingDate,
    int IsDuplicate,
    int CanonicalSourcePath,
    int PerceptualHash)
{
    public static ManifestColumnIndexes FromHeaderIndex(IReadOnlyDictionary<string, int> index)
    {
        return new ManifestColumnIndexes(
            ImportBatchId: ManifestCsv.GetRequiredIndex(index, "ImportBatchId"),
            SourcePath: ManifestCsv.GetRequiredIndex(index, "SourcePath"),
            OutputPath: ManifestCsv.GetRequiredIndex(index, "OutputPath"),
            Bucket: ManifestCsv.GetRequiredIndex(index, "Bucket"),
            Sha256: ManifestCsv.GetRequiredIndex(index, "Sha256"),
            SizeBytes: ManifestCsv.GetRequiredIndex(index, "SizeBytes"),
            Extension: ManifestCsv.GetRequiredIndex(index, "Extension"),
            Width: ManifestCsv.GetRequiredIndex(index, "Width"),
            Height: ManifestCsv.GetRequiredIndex(index, "Height"),
            Orientation: ManifestCsv.GetRequiredIndex(index, "Orientation"),
            CameraMake: ManifestCsv.GetRequiredIndex(index, "CameraMake"),
            CameraModel: ManifestCsv.GetRequiredIndex(index, "CameraModel"),
            ExifTags: index.TryGetValue("ExifTags", out var exifTags) ? exifTags : -1,
            ExifDateTimeOriginal: ManifestCsv.GetRequiredIndex(index, "ExifDateTimeOriginal"),
            ExifCreateDate: ManifestCsv.GetRequiredIndex(index, "ExifCreateDate"),
            ExifModifyDate: ManifestCsv.GetRequiredIndex(index, "ExifModifyDate"),
            FolderDateCandidate: ManifestCsv.GetRequiredIndex(index, "FolderDateCandidate"),
            CreatedAtUtc: ManifestCsv.GetRequiredIndex(index, "CreatedAtUtc"),
            LastWriteAtUtc: ManifestCsv.GetRequiredIndex(index, "LastWriteAtUtc"),
            CleanerBestDate: ManifestCsv.GetRequiredIndex(index, "CleanerBestDate"),
            CleanerBestDateSource: ManifestCsv.GetRequiredIndex(index, "CleanerBestDateSource"),
            GroupingYear: ManifestCsv.GetRequiredIndex(index, "GroupingYear"),
            GroupingDate: ManifestCsv.GetRequiredIndex(index, "GroupingDate"),
            IsDuplicate: ManifestCsv.GetRequiredIndex(index, "IsDuplicate"),
            CanonicalSourcePath: ManifestCsv.GetRequiredIndex(index, "CanonicalSourcePath"),
            PerceptualHash: ManifestCsv.GetRequiredIndex(index, "PerceptualHash"));
    }
}
